server:
  port: 8081
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql : true
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 587
    username: secu.utn@gmail.com
    password: ixqfffxeisavhrek
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
    main:
