
spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/uces?serverTimezone=GMT-3
    url: jdbc:mysql://localhost:3307/uces?serverTimezone=GMT-3
    username: root
    #password: root
    password: Renata2000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql : true
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 587
    username: secu.utn@gmail.com
    password: ixqfffxeisavhrek
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
    main:
