
spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/uces?serverTimezone=GMT-3
    url: jdbc:mysql://localhost:3307/uces?serverTimezone=GMT-3
    username: root
    #password: root
    password: Renata2000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQLBDialect
      driverClassName: com.mysql.cj.jdbc.Driver
    database: mysql