package com.example.UCESAPI.model;

public enum QuestionThemes {

    DIFFICULTY_RATING,
    PROFESSOR_RATING,
    CAREER_RATING,
    LEARNED_VALUE_RATING,
    SUBJECT_EXTRA_HOURS,
    CAREER_GENERAL_OPINION,
    CAREER_PROFESSOR_DISTINGUISHED
}
